import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import CustomNavbar from "@/components/custom_navbar";

const pd = Playfair_Display({ subsets: ["latin"], weight: ["400","500","600"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pd.className}>
        <main className="flex flex-col space-y-6 items-center bg-dark_green min-h-screen">
          <CustomNavbar />
          {children}
        </main>
      </body>
    </html>
  );
}
